add_rules("mode.debug", "mode.release", "mode.check")
add_requires("vcpkg::stringzilla")
target("dspinfo")
    set_kind("binary")
    add_files("src/*.cpp")
    set_languages("c17", "c++latest")
    add_linkdirs("C:/program files (x86)/FMOD SoundSystem/FMOD Studio API Windows/api/core/lib/x64")
    add_includedirs("C:/program files (x86)/FMOD SoundSystem/FMOD Studio API Windows/api/core/inc")
    add_syslinks("onecore")
    add_links("fmod_vc")
    add_packages("vcpkg::stringzilla")
